name: socialgene_nf

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::python>=3.10
  - conda-forge::pip
  - conda-forge::biopython>=1.79
  - conda-forge::numpy
  - bioconda::seqkit>=2.3.0
  - hcc::aspera-cli
  - bioconda::entrez-direct
  - bioconda::hmmer>=3.3.2
  - bioconda::mmseqs2>=13.45111
  - bioconda::diamond>=2.0.15
  - conda-forge::ncbi-datasets-cli>=14.13.2
  - bioconda::ncbi-genome-download>=0.3.1
  - bioconda::tabix>=1.11
  - bioconda::samtools>=1.16.1
  - conda-forge::coreutils
  - conda-forge::sed
  - conda-forge::rsync
  - conda-forge::wget
  - bioconda::grep
  - conda-forge::git
  - conda-forge::pigz>=2.6
  - conda-forge::gzip >=1.12
  - conda-forge::openjdk # required by neo4j
  - procps-ng # required by nextflow
  - zip

  - pip:
      #- git+https://github.com/socialgene/sgpy.git@c54f7d019324dc9df13cf8e2833caf70f2a315c6
      - git+https://github.com/socialgene/antismash_gbk_to_table.git@e8d8b9f83eae0305550cd3b32e53c2a11f32c69e
