name: Continuous Integration

on:
  push:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip3 install --upgrade setuptools pip
      - name: Install sg
        run: python3 -m pip install -e .[ci]
      - name: Install hmmer
        run: sudo apt-get install hmmer
      - name: Run tests
        run: pytest tests -v
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit, 'ci skip') || !contains(github.event.head_commit, 'from socialgene/release-please') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: python -m pip install flake8
      - run: flake8 --ignore E203,E501,W503
  black:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit, 'ci skip') || !contains(github.event.head_commit, 'from socialgene/release-please') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: black
        uses: psf/black@stable
