name: Linting

on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit, 'ci skip') || !contains(github.event.head_commit, 'from socialgene/release-please') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python -m pip install flake8
      - run: flake8 --ignore E203,E501,W503

  black:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit, 'ci skip') || !contains(github.event.head_commit, 'from socialgene/release-please') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: black
        uses: psf/black@stable
