name: Continuous Integration

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install sg
        run: python3 -m pip install -e .[ci]
      - name: Install hmmer
        run: sudo apt-get install hmmer
      - name: Run tests
        run: pytest tests -v --cov=./socialgene --cov-report=xml:./coverage.xml --cov-report term-missing
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
