name: Continuous Deployment
on:
  release:
    types: [published]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'skip-release')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: pip install
        run: |
          python3 -m pip install --upgrade pip setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPITEST }}
        run: |
          python3 setup.py sdist bdist_wheel
          twine upload --repository testpypi dist/*
